(function(){"use strict";
const SESSION_KEY="santivanez_private_session_v1";
const USERS={administrador:{password:"Admin2026*",rol:"Administrador",doctorId:null},recepcion:{password:"Recep2026*",rol:"Recepción",doctorId:null},medico:{password:"Medico2026*",rol:"Médico",doctorId:"med-003"}};
function session(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY));}catch(_){return null;}}
function rawLog(user,role,action,result){const items=window.PrivateStorage.list("audit");items.unshift({id:"AUD-"+Date.now(),fecha:new Date().toISOString(),usuario:user,rol:role,accion:action,resultado:result});window.PrivateStorage.save("audit",items.slice(0,500));}
function login(username,password){const key=String(username||"").trim().toLowerCase(),user=USERS[key];if(!user||user.password!==password){rawLog(key||"desconocido","Sin sesión","Intento de inicio de sesión","Rechazado");return false;}const value={usuario:key,rol:user.rol,doctorId:user.doctorId,loginAt:new Date().toISOString()};sessionStorage.setItem(SESSION_KEY,JSON.stringify(value));rawLog(key,user.rol,"Inicio de sesión simulado","Correcto");return true;}
function logout(){const active=session();if(active)rawLog(active.usuario,active.rol,"Cierre de sesión","Correcto");sessionStorage.removeItem(SESSION_KEY);location.replace("login.html");}
function roleAllowed(active,body){const allowed=String(body.dataset.allowedRoles||"").split(",").map((x)=>x.trim()).filter(Boolean);return !allowed.length||allowed.includes(active.rol);}
function protect(){if(document.body.classList.contains("login-page"))return;const active=session();if(!active){location.replace("login.html?motivo=sesion");return;}if(!roleAllowed(active,document.body)){rawLog(active.usuario,active.rol,"Intento de acceso no autorizado a "+location.pathname.split("/").pop(),"Rechazado");location.replace("dashboard.html?error=rol");return;}document.querySelectorAll("[data-roles]").forEach((element)=>{const allowed=element.dataset.roles.split(",").map((x)=>x.trim());element.hidden=!allowed.includes(active.rol);});const user=document.querySelector("#current-user"),role=document.querySelector("#current-role");if(user)user.textContent=active.usuario;if(role)role.textContent=active.rol;rawLog(active.usuario,active.rol,"Acceso a "+(location.pathname.split("/").pop()||"dashboard.html"),"Correcto");}
function initLogin(){const form=document.querySelector("#login-form");if(!form)return;const params=new URLSearchParams(location.search),notice=document.querySelector("#login-notice");if(params.get("motivo")==="sesion"){notice.className="banner banner-warning";notice.textContent="Debe iniciar sesión para acceder al entorno privado.";}form.addEventListener("submit",(event)=>{event.preventDefault();notice.replaceChildren();const username=document.querySelector("#usuario").value,password=document.querySelector("#password").value;if(login(username,password)){notice.className="banner banner-success";notice.textContent="Acceso correcto. Redirigiendo…";location.replace("dashboard.html");}else{notice.className="banner banner-error";notice.textContent="Credenciales de demostración incorrectas.";}});}
document.addEventListener("DOMContentLoaded",()=>{initLogin();protect();const logoutButton=document.querySelector("#logout-button");if(logoutButton)logoutButton.addEventListener("click",logout);});
window.PrivateAuth={USERS,session,login,logout,protect};
})();
