(function(){"use strict";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,EMAIL=/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/,PHONE=/^\+?[0-9][0-9\s-]{6,17}$/,NAME=/^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\s.'-]{2,80}$/,SAFE=/^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ0-9\s.,()'/-]{2,160}$/;
const REQUEST_KEYS=["uuid","nombre","correo","telefono","especialidad","medico","fecha","hora","motivo","estado","consentimiento","fechaRegistro"],RESPONSE_KEYS=["uuid","estado","fecha","hora","fechaActualizacion"],SENSITIVE=["historia","diagnostico","tratamiento","receta","resultado","antecedente","observacion","documentoclinico"],SPECIALTIES=["cardiologia","dermatologia","pediatria","ginecologia","traumatologia"];
function exact(obj,keys){const current=Object.keys(obj||{});return current.length===keys.length&&current.every((key)=>keys.includes(key));}
function normalizeKey(value){return String(value).normalize("NFD").replace(/[\u0300-\u036f_-]/g,"").toLowerCase();}
function sensitive(value){if(!value||typeof value!=="object")return false;return Object.keys(value).some((key)=>SENSITIVE.some((token)=>normalizeKey(key).includes(token)))||Object.values(value).some((child)=>child&&typeof child==="object"&&sensitive(child));}
function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value||"")))return false;const parts=value.split("-").map(Number),date=new Date(Date.UTC(parts[0],parts[1]-1,parts[2]));return date.getUTCFullYear()===parts[0]&&date.getUTCMonth()===parts[1]-1&&date.getUTCDate()===parts[2];}
function validate(item){const errors=[];if(!item||typeof item!=="object"||Array.isArray(item))return["La reserva debe ser un objeto JSON."];if(sensitive(item))errors.push("Se detectaron campos médicos sensibles.");if(!exact(item,REQUEST_KEYS))errors.push("Existen campos faltantes o inesperados.");if(!UUID.test(String(item.uuid||"")))errors.push("UUID inválido o ausente.");if(!NAME.test(String(item.nombre||"")))errors.push("Nombre inválido.");if(!EMAIL.test(String(item.correo||""))||String(item.correo||"").length>100)errors.push("Correo inválido.");if(!PHONE.test(String(item.telefono||"")))errors.push("Teléfono inválido.");if(!SPECIALTIES.includes(item.especialidad))errors.push("Especialidad inválida.");if(!window.PrivateStorage.list("doctors").some((row)=>row.id===item.medico))errors.push("Médico inválido.");if(!validDate(item.fecha))errors.push("Fecha inválida.");if(!/^\d{2}:\d{2}$/.test(String(item.hora||"")))errors.push("Hora inválida.");if(!SAFE.test(String(item.motivo||"")))errors.push("Motivo general inválido.");if(!["Pendiente","Cancelada"].includes(item.estado))errors.push("Estado inicial no permitido.");if(item.consentimiento!==true)errors.push("Consentimiento ausente.");if(Number.isNaN(Date.parse(item.fechaRegistro)))errors.push("Fecha de registro inválida.");return errors;}
function read(file){return new Promise((resolve,reject)=>{if(!file||(!file.name.toLowerCase().endsWith(".json")&&file.type!=="application/json"))return reject(new Error("Seleccione un archivo JSON."));if(file.size>256*1024)return reject(new Error("El archivo supera 256 KB."));const reader=new FileReader();reader.onload=()=>{try{resolve(JSON.parse(reader.result));}catch(_){reject(new Error("El contenido no es JSON válido."));}};reader.onerror=()=>reject(new Error("No se pudo leer el archivo."));reader.readAsText(file,"utf-8");});}
function download(name,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}
async function importReservation(file){const item=await read(file),errors=validate(item);if(errors.length)throw new Error(errors.join(" "));const list=window.PrivateStorage.list("appointments");if(list.some((row)=>row.uuid===item.uuid))throw new Error("El UUID ya fue importado anteriormente.");list.push(item);window.PrivateStorage.save("appointments",list);window.PrivateAudit.log("Importó reserva "+item.uuid,"Correcto");return item;}
function exportResponse(item){const response={uuid:item.uuid,estado:item.estado,fecha:item.fecha,hora:item.hora,fechaActualizacion:item.fechaActualizacion||new Date().toISOString()};if(!exact(response,RESPONSE_KEYS)||!UUID.test(response.uuid)||!validDate(response.fecha)||!/^\d{2}:\d{2}$/.test(response.hora))throw new Error("La respuesta no cumple el esquema mínimo.");download("estado-"+item.uuid+".json",response);window.PrivateAudit.log("Exportó respuesta de estado "+item.uuid,"Correcto");}
window.PrivateSync={UUID,validate,read,importReservation,exportResponse,sensitive};
})();
